/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CookieSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Mailer": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "OpenGeoIntelAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "geo-intel": {
      "type": "sst.aws.React"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}